apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/instance: test-codegen-nov624-one-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  test-codegen-nov624-one-model-server
    app.kubernetes.io/part-of: test-codegen-nov624-one  
  name: test-codegen-nov624-one-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  test-codegen-nov624-one-model-server 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  test-codegen-nov624-one-model-server
    spec:
      initContainers:
      - name: model-file
        image: quay.io/redhat-ai-dev/mistral-7b-code-16k-qlora:latest
        command: ['/usr/bin/install', '/model/model.file', '/shared/']
        volumeMounts:
        - name: model-file
          mountPath: /shared
      containers:
      - env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8001"
        - name: MODEL_PATH
          value: /model/model.file
        - name: CHAT_FORMAT
          value: openchat
        image: quay.io/ai-lab/llamacpp_python:latest
        volumeMounts:
        - name: model-file
          mountPath: /model
        name: app-model-service
        ports:
        - containerPort: 8001
        securityContext:
          runAsNonRoot: true
      volumes:
      - name: model-file
        emptyDir: {}
