apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-dsp-test-codegen-nov624-one-gitops
spec:  
  template:         
    metadata:
      name: initialize-dsp-test-codegen-nov624-one-gitops
    spec:  
      serviceAccountName: test-codegen-nov624-one-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest

        command:
        - /bin/bash
        - -c
        - |
          # Wait for the Image Stream creation job to finish
          echo "Wait for the Image Stream job"
          oc wait --for=condition=complete job/create-imagestream-test-codegen-nov624-one-gitops
          echo "Done"
          
          # Wait for the Namespace initialize job to finish
          echo "Wait for the Namespace job"
          oc wait --for=condition=complete job/initialize-namespace-test-codegen-nov624-one-gitops
          echo "Done"

          # Label the namespace as a DataScienceProject
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc label ns $NS opendatahub.io/dashboard=true --overwrite

          # Retrieve the UID for the notebook SA, and mark the notebook as owned by it for garbage collection purposes
          SA_UID=$(oc get sa test-codegen-nov624-one-dsp-job -o json | jq -r .metadata.uid)
          echo "$SA_UID"
          cat <<EOF | oc apply -f -
          apiVersion: kubeflow.org/v1
          kind: Notebook
          metadata:
            annotations:
              notebooks.opendatahub.io/inject-oauth: 'true'
              opendatahub.io/image-display-name: Minimal Python
              opendatahub.io/accelerator-name: ''
              openshift.io/description: ''
              openshift.io/display-name: test-codegen-nov624-one-notebook
              notebooks.opendatahub.io/last-image-selection: 's2i-minimal-notebook:2024.1'
              notebooks.opendatahub.io/last-size-selection: Small
            name: test-codegen-nov624-one-notebook
            namespace: rhdh-app
            ownerReferences:
              - apiVersion: v1
                kind: ServiceAccount
                name: test-codegen-nov624-one-dsp-job
                uid: $SA_UID
            labels:
              app: test-codegen-nov624-one-notebook
              opendatahub.io/dashboard: 'true'
              opendatahub.io/odh-managed: 'true'
          spec:
            template:
              spec:
                affinity: {}
                containers:
                  - resources:
                      limits:
                        cpu: '2'
                        memory: 8Gi
                      requests:
                        cpu: '1'
                        memory: 8Gi
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /notebook/rhdh-app/test-codegen-nov624-one-notebook/api
                        port: notebook-port
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 1
                    name: test-codegen-nov624-one-notebook
                    livenessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /notebook/rhdh-app/test-codegen-nov624-one-notebook/api
                        port: notebook-port
                        scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 1
                    env:
                      - name: NOTEBOOK_ARGS
                        value: |-
                          --ServerApp.port=8888
                                            --ServerApp.token=''
                                            --ServerApp.password=''
                                            --ServerApp.base_url=/notebook/rhdh-app/test-codegen-nov624-one-notebook
                                            --ServerApp.quit_button=False
                      - name: JUPYTER_IMAGE
                        value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/custom-sqlite3-odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                    envFrom:
                    - configMapRef:
                        name: test-codegen-nov624-one-model-config
                    ports:
                      - containerPort: 8888
                        name: notebook-port
                        protocol: TCP
                    imagePullPolicy: Always
                    volumeMounts:
                      - mountPath: /opt/app-root/src
                        name: test-codegen-nov624-one-notebook
                      - mountPath: /dev/shm
                        name: shm
                    image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/custom-sqlite3-odh-minimal-notebook-container:v2-2024a-20240523-sqlite3'
                    workingDir: /opt/app-root/src
                enableServiceLinks: false
                serviceAccountName: test-codegen-nov624-one-notebook
                volumes:
                  - name: test-codegen-nov624-one-notebook
                    persistentVolumeClaim:
                      claimName: test-codegen-nov624-one-notebook-rhoai
                  - emptyDir:
                      medium: Memory
                    name: shm
          ---
          kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            annotations:
              openshift.io/display-name: test-codegen-nov624-one-notebook-rhoai
            name: test-codegen-nov624-one-notebook-rhoai
            ownerReferences:
              - apiVersion: v1
                kind: ServiceAccount
                name: test-codegen-nov624-one-dsp-job
                uid: $SA_UID
            labels:
              opendatahub.io/dashboard: 'true'
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            volumeMode: Filesystem
          EOF
          
      restartPolicy: Never